### ISSUE TITLE
A a user I want to login to the app so that my data is secure. 

### ISSUE THREAD

**Issue by pdw207** [hackforwesternmass/verite#3]

**Comment by serundeputy** [comment]
pulled down and ran the migrations that @a-pasquale set up.

First had to correct the database setup in `config/database.php`

@a-pasquale if you pull this down and then add this to your local `.env` file:

```bash
DB_CONNECTION=database
DB_HOST=database
DB_PORT=3306
DB_DATABASE=laravel
DB_USERNAME=laravel
DB_PASSWORD=laravel
```

optionally you can add:
```bash
APP_URL=http://verite.lndo.site
```
Once you pull down the new code and setup `.env` run the migrations using:
```bash
lando artisan migrate
```

You can now create accounts and login to the verite site.  We will need to add the `\Auth` middleware to all routes on the site.

**Comment by a-pasquale** [comment]
@serundeputy I am still getting a Connection refused error. 

I'm also getting a connection error now with
```
lando mysql 
```
which was working before. 

Do you have anything else in your .env?

**Comment by serundeputy** [comment]
@a-pasquale sorry i was in `SF`.
here is my full `.env` file:

```
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:JzKU4X9Aag2y319agsY2ZB5v1HCAL5Iq/M0jRZt37xo=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://verite.lndo.site

DB_CONNECTION=database
DB_HOST=database
DB_PORT=3306
DB_DATABASE=laravel
DB_USERNAME=laravel
DB_PASSWORD=laravel

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
```

**Comment by serundeputy** [comment]
you might try:

```bash
lando composer install && lando composer dump-autoload
```

**Comment by a-pasquale** [comment]
Hmm, no luck with those commands or with the new .env file. Anyone else having issues with this? Could be something specific to my setup on osx? I've gotten up and running with the Homestead vm so I'm ready to keep going.

**Comment by serundeputy** [comment]
@a-pasquale I think you and @rick02840 have resolved these issues and can now login to the app.

I'm going to close this out feel free to reopen if necessary.
